version: "3"

services:
  export-worker-example-0:
    container_name: export-worker-example-0
    build: .
    image: export-worker-example:latest
    environment:
      METADATA_BROKER_LIST: '${MD_BKR_LS}'
      KAFKA_CONSUMER_GROUP_ID: 'export-worker-example'
      FILTER_CONSUMER_GROUP_ID: 'export-worker-example-0'
      FILTER_TOPIC: 'export-worker-example-filters'
    restart: unless-stopped

  export-worker-example-1:
    container_name: export-worker-example-1
    build: .
    image: export-worker-example:latest
    environment:
      METADATA_BROKER_LIST: '${MD_BKR_LS}'
      KAFKA_CONSUMER_GROUP_ID: 'export-worker-example'
      FILTER_CONSUMER_GROUP_ID: 'export-worker-example-1'
      FILTER_TOPIC: 'export-worker-example-filters'
    restart: unless-stopped